server:
  port: 8888
spring:
  datasource:
    username: root
    password: 0752root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_manager
  mail:
    host: smtp.126.com
    username: neocheung023@126.com
    password: JMLKFBDWBOLRZAFA
  jpa:
    show-sql: true
    hibernate:
      # 配置自动创建
      ddl-auto: update
